### PR TITLE
fix: fixes and simplifies autocomplete logic.

### PR DESCRIPTION
**Pull request by hhuntaa**
takes https://github.com/zkemail/archive.prove.email/issues/107 into consideration and fixes https://github.com/zkemail/archive.prove.email/issues/123

i didnt wanna mess with SearchInput.tsx too much so i just modified the autocomplete function from actions.

### CODE REVIEW

**Comment by Divide-By-0** [comment]
This isn't correct, you just disabled our fix for #107.

**Comment by hhuntaa** [comment]
weird it works for me, did you test it?
image

**Comment by hhuntaa** [comment]
more testing:
image
image

**Comment by hhuntaa** [comment]
heres postgres documentation on this:
image

and if you ever want more advanced maching you could use similarity threshold with https://www.postgresql.org/docs/current/pgtrgm.html but you have to install it first with prisma https://www.prisma.io/docs/orm/prisma-schema/postgresql-extensions#how-to-enable-the-postgresqlextensions-preview-feature:~:text=the%20hstore%2C-,pg_trgm,-and%20postgis%20extensions

**Comment by Divide-By-0** [comment]
Oh interesting. Can you try addressing these two instead: https://github.com/zkemail/archive.prove.email/issues/122 and https://github.com/zkemail/archive.prove.email/issues/101

**Comment by Divide-By-0** [comment]
Screenshot_20241030_061025_Chrome
This PR does not fix #123 by the way, since most gmail.com results are still under random ones.

**Comment by hhuntaa** [comment]
oh yeah for some reason i thought it was supposed to be like that, i was mostly thinking about the searchbar.

**Pull request closed without merging**
